language: python
dist: focal   # required for Python >= 3.7
python:
  - 3.12

services:
  - docker

env:
  - MINIO_ROOT_USER=minioadmin MINIO_ROOT_PASSWORD=minioadmin MINIO_URL=http://localhost:9000 MINIO_ACCESS_KEY=minioadmin MINIO_SECRET_KEY=minioadmin

before_install:
  - docker pull minio/minio
  - docker create -p9090:9090 -p9000:9000 -p9001:9001 minio/minio minio server /data | xargs -I{} docker start {}
  - docker ps -a

cache: pip
install:
  - pip install -r requirements.txt
  - python -m pip install -e .

script:
  - pytest