[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "v2.9.1"
name = "candigv2_authx"
dependencies = [
    "requests>=2.33.1",
    "minio>=7.2.19",
    "pytest>=9.0.3",
    "PyJWT>=2.12.0"
    ]
requires-python = ">= 3.12"
description = "Common authentication and authorization methods for CanDIGv2"
readme = "README.md"

[project.urls]
Repository = "https://github.com/CanDIG/candigv2-authx"
