[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
version = "v2.8.6"
name = "candigv2_authx"
dependencies = [
    "requests>=2.32.2",
    "minio>=7.2.12",
    "pytest>=8.3.3",
    "PyJWT>=2.6.0",
    "cryptography>=43.0.1"
    ]
requires-python = ">= 3.9"
description = "Common authentication and authorization methods for CanDIGv2"
readme = "README.md"

[project.urls]
Repository = "https://github.com/CanDIG/candigv2-authx"
